In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
LEARNING_RATE = 0.01
ITER_NUM = 10_000

## 1. Load Data

In [3]:
# Data for the and operation.
and_inputs = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]
and_outputs = [
    [0],
    [0],
    [0],
    [1]
]

# Training set.
and_train_examples = torch.tensor(and_inputs, dtype=torch.float)
and_train_labels = torch.tensor(and_outputs, dtype=torch.float)

# Test set.
and_test_examples = torch.tensor(and_inputs, dtype=torch.float)
and_test_labels = torch.tensor(and_outputs, dtype=torch.float)

In [4]:
print(and_train_examples)
print(and_train_labels)

print(and_test_examples)
print(and_test_labels)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.]])
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.]])


## 2. Build a Model

In [5]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.linear = nn.Linear(2, 1)
        
    def forward(self, inputs):
        z1 = self.linear(inputs)
        a1 = torch.sigmoid(z1)

        return a1

In [6]:
net = Net()

## 3. Criterion and Optimizer

In [7]:
# Criterion.
criterion = nn.MSELoss()

In [8]:
# Optimizer.
optim = optim.SGD(params=net.parameters(), lr=LEARNING_RATE)

## 4. Train the Model

In [9]:
running_loss = 0.0
training_set_size = and_train_examples.size()[0]
for i in range(ITER_NUM):
    optim.zero_grad()
    
    # Forward.
    outputs = net(and_train_examples)
    loss = criterion(outputs, and_train_labels)

    # Backward.
    loss.backward()
    
    # Updates params.
    optim.step()
    
    if i % 200 == 199:
        print(f"iteration: {i:>4}, loss: {loss / training_set_size:.6f}")
        
        running_loss = 0.0

iteration:  199, loss: 0.045905
iteration:  399, loss: 0.043811
iteration:  599, loss: 0.041936
iteration:  799, loss: 0.040227
iteration:  999, loss: 0.038651
iteration: 1199, loss: 0.037192
iteration: 1399, loss: 0.035836
iteration: 1599, loss: 0.034574
iteration: 1799, loss: 0.033398
iteration: 1999, loss: 0.032300
iteration: 2199, loss: 0.031274
iteration: 2399, loss: 0.030313
iteration: 2599, loss: 0.029411
iteration: 2799, loss: 0.028564
iteration: 2999, loss: 0.027767
iteration: 3199, loss: 0.027015
iteration: 3399, loss: 0.026304
iteration: 3599, loss: 0.025631
iteration: 3799, loss: 0.024993
iteration: 3999, loss: 0.024387
iteration: 4199, loss: 0.023810
iteration: 4399, loss: 0.023260
iteration: 4599, loss: 0.022736
iteration: 4799, loss: 0.022235
iteration: 4999, loss: 0.021756
iteration: 5199, loss: 0.021297
iteration: 5399, loss: 0.020856
iteration: 5599, loss: 0.020434
iteration: 5799, loss: 0.020027
iteration: 5999, loss: 0.019637
iteration: 6199, loss: 0.019260
iteratio

In [10]:
params = list(net.parameters())
theta_1 = params[0][0][0]
theta_2 = params[0][0][1]
bias = params[1][0]

print(f"theta1 = {theta_1:.2f}, theta2 = {theta_2:.2f}, bias = {bias:.2f}")

theta1 = 1.88, theta2 = 1.90, bias = -2.99


## 5. Test the Model

In [11]:
def test(inputs):
    inputs = torch.tensor(inputs, dtype=torch.float)
    outputs = net(inputs)
    
    z = theta_1 * inputs[0] + theta_2 * inputs[1] + bias
    y_hat = 1 / (1 + torch.exp(-z))
    
    result = y_hat > 0.5 ? 1
    
    print("%d && %d: %d" % (inputs[0], inputs[1], y_hat))
    
test([0, 0])
test([0, 1])
test([1, 0])
test([1, 1])

tensor(0.0479, grad_fn=<MulBackward0>)
0 && 0: 0
tensor(0.2518, grad_fn=<MulBackward0>)
0 && 1: 0
tensor(0.2481, grad_fn=<MulBackward0>)
1 && 0: 0
tensor(0.6881, grad_fn=<MulBackward0>)
1 && 1: 0
