In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
LEARNING_RATE = 0.01
ITER_NUM = 5_000

## 1. Load Data

In [3]:
# Data for the and operation.
and_inputs = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]
and_outputs = [
    [0],
    [0],
    [0],
    [1]
]

In [4]:
# Training set.
and_train_examples = torch.tensor(and_inputs, dtype=torch.float)
and_train_labels = torch.tensor(and_outputs, dtype=torch.float)

# Test set.
and_test_examples = torch.tensor(and_inputs, dtype=torch.float)
and_test_labels = torch.tensor(and_outputs, dtype=torch.float)

## 2. Build a Model

In [5]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.linear = nn.Linear(2, 1)
        
    def forward(self, inputs):
        z1 = self.linear(inputs)
        a1 = torch.sigmoid(z1)  # (i)

        return a1

<font color=red>
    (i) Activation func is necessary. sign() is used in the original perceptron.
</font>

In [6]:
net = Net()

## 3. Criterion and Optimizer

In [7]:
# Criterion.
criterion = nn.MSELoss()

In [8]:
# Optimizer.
optim = optim.SGD(params=net.parameters(), lr=LEARNING_RATE)

## 4. Train the Model

In [9]:
running_loss = 0.0
training_set_size = and_train_examples.size()[0]
for i in range(ITER_NUM):
    optim.zero_grad()
    
    # Forward.
    outputs = net(and_train_examples)
    loss = criterion(outputs, and_train_labels)

    # Backward.
    loss.backward()
    
    # Updates params.
    optim.step()
    
    if i % 200 == 199:
        print(f"iteration: {i:>4}, loss: {loss / training_set_size:.6f}")
        
        running_loss = 0.0

tensor([[-0.0388, -0.0298]])
tensor([[-0.0388, -0.0298]])
tensor([[-0.0389, -0.0298]])
tensor([[-0.0389, -0.0298]])
tensor([[-0.0389, -0.0298]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0389, -0.0299]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0300]])
tensor([[-0.0390, -0.0301]])
tensor([[-0.0390, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0301]])
tensor([[-0.0391, -0.0302]])
tensor([[-0.0391, -0.0302]])
tensor([[-0.03

tensor([[-0.0419, -0.0335]])
tensor([[-0.0419, -0.0335]])
tensor([[-0.0419, -0.0335]])
tensor([[-0.0419, -0.0336]])
tensor([[-0.0419, -0.0336]])
tensor([[-0.0419, -0.0336]])
tensor([[-0.0419, -0.0336]])
tensor([[-0.0420, -0.0336]])
tensor([[-0.0420, -0.0336]])
tensor([[-0.0420, -0.0336]])
tensor([[-0.0420, -0.0336]])
tensor([[-0.0420, -0.0336]])
tensor([[-0.0420, -0.0337]])
tensor([[-0.0420, -0.0337]])
tensor([[-0.0420, -0.0337]])
tensor([[-0.0420, -0.0337]])
tensor([[-0.0420, -0.0337]])
tensor([[-0.0420, -0.0337]])
tensor([[-0.0421, -0.0337]])
tensor([[-0.0421, -0.0337]])
tensor([[-0.0421, -0.0337]])
tensor([[-0.0421, -0.0337]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0421, -0.0338]])
tensor([[-0.0422, -0.0338]])
tensor([[-0.0422, -0.0338]])
tensor([[-0.0422, -0.0339]])
tensor([[-0.0422, -0.0339]])
tensor([[-0.0422, -0.0339]])
tensor([[-0.04

tensor([[-0.0444, -0.0365]])
tensor([[-0.0444, -0.0365]])
tensor([[-0.0444, -0.0365]])
tensor([[-0.0445, -0.0365]])
tensor([[-0.0445, -0.0365]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0445, -0.0366]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0367]])
tensor([[-0.0446, -0.0368]])
tensor([[-0.0446, -0.0368]])
tensor([[-0.0446, -0.0368]])
tensor([[-0.0447, -0.0368]])
tensor([[-0.0447, -0.0368]])
tensor([[-0.04

tensor([[-0.0462, -0.0387]])
tensor([[-0.0462, -0.0387]])
tensor([[-0.0462, -0.0387]])
tensor([[-0.0462, -0.0387]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.0462, -0.0388]])
tensor([[-0.04

tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0385]])
tensor([[-0.0453, -0.0384]])
tensor([[-0.0453, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0452, -0.0384]])
tensor([[-0.0451, -0.0384]])
tensor([[-0.0451, -0.0384]])
tensor([[-0.0451, -0.0384]])
tensor([[-0.0451, -0.0384]])
tensor([[-0.04

tensor([[-0.0414, -0.0353]])
tensor([[-0.0414, -0.0353]])
tensor([[-0.0414, -0.0353]])
tensor([[-0.0414, -0.0353]])
tensor([[-0.0414, -0.0353]])
tensor([[-0.0414, -0.0353]])
tensor([[-0.0414, -0.0353]])
tensor([[-0.0413, -0.0353]])
tensor([[-0.0413, -0.0353]])
tensor([[-0.0413, -0.0353]])
tensor([[-0.0413, -0.0352]])
tensor([[-0.0413, -0.0352]])
tensor([[-0.0413, -0.0352]])
tensor([[-0.0413, -0.0352]])
tensor([[-0.0413, -0.0352]])
tensor([[-0.0413, -0.0352]])
tensor([[-0.0412, -0.0352]])
tensor([[-0.0412, -0.0352]])
tensor([[-0.0412, -0.0352]])
tensor([[-0.0412, -0.0352]])
tensor([[-0.0412, -0.0352]])
tensor([[-0.0412, -0.0351]])
tensor([[-0.0412, -0.0351]])
tensor([[-0.0412, -0.0351]])
tensor([[-0.0412, -0.0351]])
tensor([[-0.0411, -0.0351]])
tensor([[-0.0411, -0.0351]])
tensor([[-0.0411, -0.0351]])
tensor([[-0.0411, -0.0351]])
tensor([[-0.0411, -0.0351]])
tensor([[-0.0411, -0.0351]])
tensor([[-0.0411, -0.0350]])
tensor([[-0.0411, -0.0350]])
tensor([[-0.0411, -0.0350]])
tensor([[-0.04

tensor([[-0.0368, -0.0314]])
tensor([[-0.0368, -0.0314]])
tensor([[-0.0368, -0.0314]])
tensor([[-0.0367, -0.0314]])
tensor([[-0.0367, -0.0314]])
tensor([[-0.0367, -0.0314]])
tensor([[-0.0367, -0.0314]])
tensor([[-0.0367, -0.0314]])
tensor([[-0.0367, -0.0313]])
tensor([[-0.0367, -0.0313]])
tensor([[-0.0367, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0313]])
tensor([[-0.0366, -0.0312]])
tensor([[-0.0366, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0365, -0.0312]])
tensor([[-0.0364, -0.0311]])
tensor([[-0.0364, -0.0311]])
tensor([[-0.0364, -0.0311]])
tensor([[-0.0364, -0.0311]])
tensor([[-0.0364, -0.0311]])
tensor([[-0.03

tensor([[-0.0324, -0.0278]])
tensor([[-0.0324, -0.0278]])
tensor([[-0.0324, -0.0278]])
tensor([[-0.0324, -0.0278]])
tensor([[-0.0324, -0.0278]])
tensor([[-0.0324, -0.0277]])
tensor([[-0.0324, -0.0277]])
tensor([[-0.0324, -0.0277]])
tensor([[-0.0324, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0277]])
tensor([[-0.0323, -0.0276]])
tensor([[-0.0323, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0322, -0.0276]])
tensor([[-0.0321, -0.0276]])
tensor([[-0.0321, -0.0275]])
tensor([[-0.0321, -0.0275]])
tensor([[-0.0321, -0.0275]])
tensor([[-0.0321, -0.0275]])
tensor([[-0.03

tensor([[-0.0289, -0.0249]])
tensor([[-0.0289, -0.0249]])
tensor([[-0.0289, -0.0249]])
tensor([[-0.0289, -0.0249]])
tensor([[-0.0288, -0.0249]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0288, -0.0248]])
tensor([[-0.0287, -0.0248]])
tensor([[-0.0287, -0.0248]])
tensor([[-0.0287, -0.0248]])
tensor([[-0.0287, -0.0248]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0287, -0.0247]])
tensor([[-0.0286, -0.0247]])
tensor([[-0.0286, -0.0247]])
tensor([[-0.0286, -0.0247]])
tensor([[-0.0286, -0.0247]])
tensor([[-0.02

tensor([[-0.0261, -0.0227]])
tensor([[-0.0261, -0.0227]])
tensor([[-0.0261, -0.0227]])
tensor([[-0.0261, -0.0227]])
tensor([[-0.0261, -0.0227]])
tensor([[-0.0261, -0.0226]])
tensor([[-0.0261, -0.0226]])
tensor([[-0.0261, -0.0226]])
tensor([[-0.0261, -0.0226]])
tensor([[-0.0261, -0.0226]])
tensor([[-0.0261, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0226]])
tensor([[-0.0260, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.0259, -0.0225]])
tensor([[-0.02

tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0209]])
tensor([[-0.0238, -0.0208]])
tensor([[-0.0238, -0.0208]])
tensor([[-0.0238, -0.0208]])
tensor([[-0.0238, -0.0208]])
tensor([[-0.0238, -0.0208]])
tensor([[-0.0238, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.0237, -0.0208]])
tensor([[-0.02

tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0218, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0193]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.0217, -0.0192]])
tensor([[-0.02

tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0182]])
tensor([[-0.0203, -0.0181]])
tensor([[-0.0203, -0.0181]])
tensor([[-0.0203, -0.0181]])
tensor([[-0.0203, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.0202, -0.0181]])
tensor([[-0.02

<font color=red>
    (i) Check grad: 
    <br/>
    net.linear.weight.grad  # `weight` has multiple values
    <br/>
    net.linear.bias.grad
</font>

In [10]:
params = list(net.parameters())
theta_1 = params[0][0][0]
theta_2 = params[0][0][1]
bias = params[1][0]

print(f"theta1 = {theta_1:.2f}, theta2 = {theta_2:.2f}, bias = {bias:.2f}")

theta1 = 1.03, theta2 = 1.08, bias = -1.82


## 5. Test the Model

In [11]:
def test(inputs):
    inputs = torch.tensor(inputs, dtype=torch.float)
    outputs = net(inputs)
    
    z = theta_1 * inputs[0] + theta_2 * inputs[1] + bias
    y_hat = 1 / (1 + torch.exp(-z))
    
    result = 1 if y_hat > 0.5 else 0
    
    print("%d && %d: %d" % (inputs[0], inputs[1], result))
    
test([0, 0])
test([0, 1])
test([1, 0])
test([1, 1])

0 && 0: 0
0 && 1: 0
1 && 0: 0
1 && 1: 1
